VERSION 0.7
FROM python:3.10
WORKDIR /contrib


src-files:
  COPY electricitymap ./electricitymap
  COPY web/public/locales/en.json ./web/public/locales/en.json
  COPY __init__.py ./__init__.py
  COPY pyproject.toml .
  SAVE ARTIFACT .

prepare:
  FROM +src-files
  RUN echo "prepare contrib"