VERSION --use-visited-upfront-hash-collection 0.7
FROM python:3.10
WORKDIR /libs/pkg-tooling

src-files:
  COPY ../../contrib+src-files/* /contrib
  COPY electricitymap ./electricitymap
  COPY pyproject.toml .
  SAVE ARTIFACT .

prepare:
  FROM +src-files
  RUN echo "prepare pkg-tooling"