VERSION --use-visited-upfront-hash-collection 0.7
FROM python:3.10
WORKDIR /libs/cloud-storage

src-files:
  COPY ../../contrib+src-files/* /contrib
  COPY ../../libs/pkg-tooling+src-files/* /libs/pkg-tooling
  COPY electricitymap ./electricitymap
  COPY pyproject.toml .
  SAVE ARTIFACT .

prepare:
  FROM +src-files
  RUN echo "running cloud-storage lib"